ALTER TABLE squadov.riot_accounts
ALTER COLUMN game_name DROP NOT NULL,
ALTER COLUMN game_name DROP DEFAULT,
ALTER COLUMN tag_line DROP NOT NULL,
ALTER COLUMN tag_line DROP DEFAULT,
ALTER COLUMN account_id DROP NOT NULL,
ALTER COLUMN account_id DROP DEFAULT,
ALTER COLUMN summoner_id DROP NOT NULL,
ALTER COLUMN summoner_id DROP DEFAULT,
ALTER COLUMN summoner_name DROP NOT NULL,
ALTER COLUMN summoner_name DROP DEFAULT;