ALTER TABLE user_profiles
ADD COLUMN facebook VARCHAR,
ADD COLUMN instagram VARCHAR,
ADD COLUMN twitch VARCHAR,
ADD COLUMN youtube VARCHAR,
ADD COLUMN snapchat VARCHAR,
ADD COLUMN twitter VARCHAR,
ADD COLUMN tiktok VARCHAR,
ADD COLUMN misc_access VARCHAR;